# Generated by Django 2.2.4 on 2019-09-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('clgname', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
    ]
