# Generated by Django 2.2.4 on 2019-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='emailid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
