# Generated by Django 2.2.4 on 2019-09-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_registration_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='emailid',
        ),
    ]
