# Generated by Django 2.2.4 on 2019-09-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_auto_20190919_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjectnames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
