# Generated by Django 2.2.4 on 2019-09-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=50)),
                ('subname', models.CharField(max_length=50)),
                ('marksvalue', models.CharField(max_length=10)),
                ('marks', models.CharField(max_length=10)),
            ],
        ),
    ]
